---
inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/TrailingCommaInHashLiteral:
  Enabled: True
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  Enabled: True
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  Enabled: True
  EnforcedStyleForMultiline: consistent_comma
